In [1]:
%%HTML
<h1>Numpy </h1>

In [2]:
%%HTML
<h1>Creating arrays in Numpy</h1>
<h4>Method 1: Casting the list into an array </h4>

In [3]:
my_list =[1,2,3,4]
import numpy as np 
arr=np.array(my_list)
arr

array([1, 2, 3, 4])

In [4]:
my_list2=[[1,2,3],[4,5,6],[7,8,9]]
np.array(my_list2)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
%%HTML
<h4>Method 2: using Numpy's built in methods for creation of arrays </h4>

In [6]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [8]:
np.arange(1,11,5)

array([1, 6])

In [9]:
%%HTML
<h4>Method 3: creating arrays with zeros and ones</h4>

In [10]:
np.zeros(5)

array([ 0.,  0.,  0.,  0.,  0.])

In [11]:
np.zeros((2,2))

array([[ 0.,  0.],
       [ 0.,  0.]])

In [12]:
np.ones(4)

array([ 1.,  1.,  1.,  1.])

In [24]:
np.ones((3,3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [25]:
np.eye(5)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [14]:
%%HTML
<h1>Method 4: Using linspace </h1>

In [15]:
np.linspace(1,11,5)

array([  1. ,   3.5,   6. ,   8.5,  11. ])

In [16]:
np.linspace(1,100,2)

array([   1.,  100.])

In [20]:
np.linspace(0,101,5)

array([   0.  ,   25.25,   50.5 ,   75.75,  101.  ])

In [21]:
%%HTML
<h1>using random.rand</h1>

In [22]:
np.random.rand(5)

array([ 0.76118913,  0.56155958,  0.94332472,  0.35364315,  0.60932945])

In [23]:
np.random.rand(5,5)

array([[ 0.65986238,  0.5009505 ,  0.49760761,  0.77046051,  0.92480771],
       [ 0.83546525,  0.21189529,  0.10396354,  0.23959434,  0.75377508],
       [ 0.36896881,  0.41686231,  0.03236812,  0.63678881,  0.56523521],
       [ 0.97314492,  0.44487781,  0.80024321,  0.26016832,  0.91300444],
       [ 0.07913556,  0.33415575,  0.89622477,  0.3834017 ,  0.55321356]])

In [26]:
%%HTML
<h4>using random.randn gives elements from a normal distribution, using random.randint gives integers by taking low and high value range. </h4>

In [27]:
np.random.randn(4)

array([-1.18257286, -0.06014165,  0.54139545, -0.59521979])

In [28]:
np.random.randn(3,3)

array([[-1.61312026, -2.04137846, -0.62608436],
       [ 0.92232667,  1.14522988,  0.50284288],
       [-0.58047437, -0.81567041, -1.73574643]])

In [29]:
np.random.randint(1,100,14)

array([61,  1, 47, 53, 39, 18, 27, 46, 79,  1, 17, 58, 49, 91])

In [30]:
%%HTML
<h1>Some Useful Methods for arrays</h1>

In [31]:
arr1=np.arange(25)

In [32]:
arr2=np.random.randint(0,100,25)

In [33]:
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [34]:
arr1.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [35]:
arr2.max()

99

In [36]:
arr2.min()

4

In [38]:
arr2.shape

(25,)

In [39]:
arr1.shape

(25,)

In [40]:
arr2.argmax()

4

In [41]:
arr2.argmin()


18

In [43]:
arr1.dtype

dtype('int64')

In [1]:
%%HTML
<h1>Indexing in Arrays</h1>
<h3>Similar to Lists in Python</h3>

In [4]:
import numpy as np
a=np.arange(0,11)

In [5]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
a[0]

0

In [7]:
a[0:5]

array([0, 1, 2, 3, 4])

In [8]:
b=a[0:5]

In [9]:
b

array([0, 1, 2, 3, 4])

In [10]:
b[:]=100

In [11]:
b

array([100, 100, 100, 100, 100])

In [12]:
a

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [13]:
%%HTML
<h1>whenever u make changes in b, it also gets reflected in a . This is because python does not create new array.</h1>

In [14]:
%%HTML
<h1>for creating new arrays, we should use .copy() </h1>

In [15]:
c=a.copy()

In [16]:
c

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [17]:
c[:]=111

In [18]:
c

array([111, 111, 111, 111, 111, 111, 111, 111, 111, 111, 111])

In [19]:
a

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [20]:
%%HTML
<h1>2-D arrays Indexing</h1>

In [21]:
import numpy as np
x=np.array([[1,2,3],[4,5,6],[6,5,4]])

In [22]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [6, 5, 4]])

In [23]:
x[0][1]

2

In [24]:
x[0,1]

2

In [25]:
x[1:,:]

array([[4, 5, 6],
       [6, 5, 4]])

In [26]:
%%HTML
<h1>Conditional Selection in numpy</h1>

In [27]:
sample=np.arange(0,11)

In [28]:
sample

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [29]:
test=sample>5

In [30]:
test

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True], dtype=bool)

In [31]:
sample[test]

array([ 6,  7,  8,  9, 10])

In [32]:
sample[sample > 5]

array([ 6,  7,  8,  9, 10])

In [33]:
%%HTML
<h1>numpy operations</h1>

In [34]:
%%HTML
<h1>1.Arrays with arrays</h1>
<h1>2.Arrays with scalar</h1>
<h1>3.Universal Operations with numpy</h1>

In [35]:
%%HTML
<h3>1.Arrays with arrays</h3>

In [36]:
ar=np.arange(0,11)

In [37]:
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [38]:
ar + ar

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [39]:
ar - ar

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [40]:
ar * ar

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [41]:
%%HTML
<h3>2.Arrays with scalar</h3>

In [43]:
ar * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [44]:
ar + 2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [45]:
ar - 4

array([-4, -3, -2, -1,  0,  1,  2,  3,  4,  5,  6])

In [46]:
ar ** 4

array([    0,     1,    16,    81,   256,   625,  1296,  2401,  4096,
        6561, 10000])

In [47]:
%%HTML
<h3>3.Universal Functions with numpy</h3>

In [48]:
np.sqrt(ar)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

In [49]:
np.log(ar)

/Users/saikrishna/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([       -inf,  0.        ,  0.69314718,  1.09861229,  1.38629436,
        1.60943791,  1.79175947,  1.94591015,  2.07944154,  2.19722458,
        2.30258509])

In [50]:
np.exp(ar)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03,   2.20264658e+04])

In [51]:
np.max(ar)

10